version: 0.2

phases:
  install:
    commands:
      - npm install -g @angular/cli

  build:
    commands:
      - echo Linting project...
      - ng lint

  post_build:
    commands:
      - echo Linting completed!
